config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :users }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :puppies do
    resources :bookings, only: [:new, :create, :show] do
      get 'confirm', to: "bookings#confirm"
    end
  end
  resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create, :show]
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :puppy
  belongs_to :user
  validates_presence_of :start_date, :end_date, :total_price
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show]
  before_action :set_puppy, only: [:new, :show, :confirm, :create]
  skip_before_action :authenticate_user!, only: [:new]

  def index
    @bookings = Booking.where("user_id = ?", current_user.id)
    @printed = false
    @reviews = Review.where("user_id = ?", current_user.id)
  end

  def new
  end

  def show
    total_price = (@booking.end_date - @booking.start_date).to_i / 24 / 60 / 60 * @puppy.daily_price
    @booking.total_price = total_price
  end

  def confirm
    @booking = Booking.find(params[:booking_id])
    total_price = (@booking.end_date - @booking.start_date).to_i / 24 / 60 / 60 * @puppy.daily_price
    @booking.total_price = total_price
    @booking.confirmed = true
    @booking.save
    redirect_to puppy_booking_path(@puppy, @booking)
  end

  def create
    # Store dates from params as actual dates and not string
    @start_date = DateTime.parse(booking_params["start_date"])
    @end_date = DateTime.parse(booking_params["end_date"])

    @string = check_dates(@start_date, @end_date, @puppy)

    if @string == "true"
      @booking = Booking.new(booking_params)
      @booking.puppy = @puppy
      @booking.user_id = current_user.id

      # Calculate Total Price depending on selected time period
      total_price = (@end_date - @start_date).to_i * @puppy.daily_price
      @booking.total_price = total_price

      if @booking.save
        redirect_to puppy_booking_path(@puppy, @booking)
      else
        redirect_to puppy_path(@puppy)
      end
    else
      redirect_to puppy_path(@puppy), notice: @string
    end
  end

  private

  def check_dates(start_date, end_date, puppy)
    today = Date.today

    # Check whether date is in future
    # Check whether end_date is after start_date
    if end_date - start_date < 0
      @string = "Please pick an end date after the start date"
    elsif (start_date - today).to_i < 0
      @string = "Please pick a start date in the future"
    elsif (end_date - today).to_i < 0
      @string = "Please pick a start date in the future"
    else
      # Check whether Puppy available
      if check_puppy_available(start_date, end_date, puppy)
        @string = "true"
      else
        @string = "Sorry, Puppy #{puppy.name} is already booked for the selected time period."
      end
    end
    return @string
  end

  def check_puppy_available(start_date, end_date, puppy)
    # Make sure only to check for bookings that are CONFIRMED
    @all_bookings = puppy.bookings.where("confirmed = ? ", true)
    # If there are no confirmed bookings, puppy is available
    if @all_bookings.empty?
      @value = true
    else
      # If there are confirmed bookings, check whether dates overlap
      @all_bookings.each do |booking|
        @value = booking.start_date <= end_date && booking.end_date <= start_date
      end
    end
    return @value
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_puppy
    @puppy = Puppy.find(params[:puppy_id])
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@puppy, @booking] do |f| %>
  <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>

  <%= hidden_field_tag 'total_price', @puppy.daily_price %>
  <p>Price per Day: <%= number_with_precision((@puppy.daily_price.to_f / 100).round(2), precision: 2) %> €</p>

  <%= f.submit "Book Now", class: "btn btn-lg btn-primary" %>
<% end %>

app/views/bookings/index.html.erb
<div class="dark-gray">
  <h1>My Bookings</h1>
</div>

<div class="container">


  <% @bookings.each do |booking| %>

    <% if booking.confirmed %>
    <% @printed = true %>

    <div class="card-puppy">
      <h4>Your booking of <%= booking.puppy.name %></h4>
      <div class="booking-text">
        <p><strong>Start Date: </strong><%= booking.start_date.strftime("%d %B %Y") %></p>
        <p><strong>End Date: </strong><%= booking.end_date.strftime("%d %B %Y") %></p>
        <p><strong>Total Price: </strong><%= number_with_precision((booking.total_price.to_f / 100).round(2), precision: 2) %> €</p>
        <p><strong><%= link_to "Add a Review", new_booking_review_path(booking) %></strong></p>
        <%= link_to "View details" , puppy_booking_path(booking.puppy, booking), class: "btn btn-primary" %>

        </div>
      </div>
    <% end %>

  <% end %>


  <% if !@printed %>
  <h3>Sorry, you do not have any confirmed bookings yet.</h3>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<div class="dark-gray">
  <h1>Booking Confirmation</h1>
</div>


  <div class="full-width">
    <div class="flex-horizontal">
      <div class="flex-item gray-ground">
        <% if @booking.confirmed? %>
      <div class="container whitebox">
        <div class="booking-text-container">
        <div class="confirmed-text">
          <p>Arf arf! Your booking is confirmed. <%= @puppy.name %> can't wait to meet you! </p>
          <br>
        </div>
        </div>


        <%= image_tag(@puppy.photo_url, class: "confirmation2-image", alt: "puppy pic") %>
        <br>
        <br>
      <div class="booking-text-container">
        <%= link_to 'Back to all Puppies' , puppies_path %>
      </div>
      </div>
        <br>

        <% else %>

        <div class="container whitebox">
          <div class="booking-intro">
            <p>Hey, thanks for choosing <%= @puppy.name %>. You'll love him!</p>
            <p>Please confirm your booking below.</p>
          </div>
          <%= image_tag(@puppy.photo_url, class: "confirmation1-image", alt: "puppy pic") %>

          <div class="booking-text-container">
            <div class="booking-text">
              <p><strong>Name of Puppy: </strong><%= @puppy.name %></p>
              <p><strong>Start Date: </strong><%= @booking.start_date.strftime("%d %B %Y") %></p>
              <p><strong>End Date: </strong><%= @booking.end_date.strftime("%d %B %Y") %></p>
              <p><strong>Total Price: </strong><%= number_with_precision((@booking.total_price.to_f / 100).round(2), precision: 2) %> €</p>

              <p><strong>Pick <%= @puppy.name %> up at: </strong> <%= @puppy.street %>, <%= @puppy.city %>, <%= @puppy.country %></p>
            </div>
          </div>
          <br>
          <div>
            <%= link_to 'Confirm', puppy_booking_confirm_path(@puppy, @booking), class: "btn btn-lg btn-primary btn-confirmation1" %>
          </div>
        </div>

        <% end %>
      </div>
    </div>
  </div>