config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :users }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :puppies do
    resources :bookings, only: [:new, :create, :show] do
      get 'confirm', to: "bookings#confirm"
    end
  end
  resources :bookings, only: [:index] do
    resources :reviews, only: [:new, :create, :show]
  end
end

app/models/puppy.rb
class Puppy < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :user
  belongs_to :breed

  validates_presence_of :photo_url, :name, :description, :street, :zipcode, :city, :daily_price, :birthdate, :toilet_training_level, :title

  validates :toilet_training_level, inclusion: { in: [1, 2, 3, 4, 5] }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_street?

  def address
    "#{street}, #{zipcode}, #{city}, #{country}"
  end
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_action :set_puppy, only: [:show, :update, :destroy]
  before_action :set_puppy_for_edit, only: [:edit]
  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    @puppies_query = Puppy.near("%#{params[:city]}%", 2000)
    @query = params[:city]

    if @puppies_query.any?
      @puppies = @puppies_query
    else
      @puppies = Puppy.near("Milan", 50)
    end

    if params[:price_from] and params[:price_to]
      @puppies = @puppies.where("daily_price <= ? AND daily_price >= ?", params[:price_to].to_i * 100, params[:price_from].to_i * 100)
    end

    @markers = @puppies.map do |puppy|
      {
        lat: puppy.latitude,
        lng: puppy.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end

    @body_class = "extra-padding"

  end

  def show
    @booking = Booking.new
    @reviews = Review.where("puppy_id = ?", params[:id])
  end

  def new
    @puppy = Puppy.new
  end

  def create
    # price_in_cents = puppy_params[:daily_price].to_f.round(2) * 100
    # puppy_params[:daily_price] = price_in_cents.to_i.to_s
    @puppy = Puppy.new(puppy_params)
    @puppy.user = current_user
    if @puppy.save
      redirect_to puppy_path(@puppy)
    else
      render :new
    end
  end

  def edit
    # User that clicks has to be user that created puppy
    if @puppy.user.id == current_user.id

    else
      redirect_to puppy_path(@puppy)
    end
  end

  def update
    if @puppy.user.id == current_user.id
      @puppy.update(puppy_params)
      redirect_to puppy_path(@puppy)
    else
      redirect_to puppy_path(@puppy)
    end
  end

  def destroy
    if @puppy.user.id == current_user.id
      @puppy.destroy
      redirect_to puppies_path
    else
      redirect_to puppy_path(@puppy)
    end
  end

  private

  def puppy_params
    price_in_cents = params[:puppy][:daily_price].to_f.round(2) * 100
    params[:puppy][:daily_price] = price_in_cents.to_i
    params.require(:puppy).permit(:name, :photo_url, :description, :street, :zipcode, :city, :country, :daily_price, :birthdate, :toilet_training_level, :breed_id, :title)
  end

  def set_puppy
    @puppy = Puppy.find(params[:id])
  end

  def set_puppy_for_edit
    @puppy = Puppy.find(params[:id])
    @puppy.daily_price = @puppy.daily_price.to_f / 100
    @puppy
  end
end

app/views/puppies/_form.html.erb
  <div class="flex-container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 padding">
      <%= simple_form_for [@puppy] do |f| %>
      <%= f.input :title, label: "Title of your offer" %>
      <%= f.input :name, label: "Name of Puppy" %>
      <%= f.input :birthdate, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :toilet_training_level, :as => :grouped_select,
      :collection => { [1,2,3,4,5] => 'Levels - 1: Low to 5: High' },
      :group_method => :first,
      :group_label_method => :last %>
      <%= f.association :breed, include_hidden: false %>
    </div>


    <div class="col-xs-12 col-sm-6 padding">
      <%= f.input :street %>
      <%= f.input :zipcode %>
      <%= f.input :city %>
      <%= f.input :country, as: :string %>
      <%= f.input :daily_price, label: "Daily Price in Euros (ex: 10.78€)" %>
      <%= f.input :photo_url %>
    </div>
  </div>
    <div class="flex-container block padding1">
      <%= f.input :description, label: "Describe your puppy"%>
      <div class="row padding1">
      <%= f.submit "Save Puppy", class: "col-xs-12 col-md-3 btn btn-primary btn-lg margin"%>
      </div>
    </div>
      <% end %>
</div>

app/views/puppies/edit.html.erb
<h1>Puppies#edit</h1>
<p>Find me in app/views/puppies/edit.html.erb</p>


</div>
  <%= render "puppies/form", puppy: @puppy%>
</div>

app/views/puppies/index.html.erb
<div class="content">

  <div class="container index-container">
    <div class="row">
      <div class="index-message">
        <% if @puppies_query.empty? %>
          <h2>Wuff, we couldn't find puppies for <%= @query %>.</h2>
          <h4>Check out some of our Puppies in Milan instead.</h4>
        <% else %>
          <h4>We found <strong><%= @puppies.length %></strong> results for your location</h4>
        <% end %>
        <%=  link_to "Start new Search", root_path%>
      </div>
      <% @puppies.each do |puppy| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= puppy.photo_url %>');">
          <div class="card-category"><%= puppy.name %></div>
          <div class="card-description">
            <h2><%= puppy.title %></h2>
            <p><%= number_with_precision((puppy.daily_price.to_f / 100).round(2), precision: 2) %> €</p>
          </div>
          <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/random">
          <a class="card-link" href="<%= puppy_path(puppy) %>" ></a>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="container map-container">
    <div id="map" data-markers="<%= @markers.to_json %>">
    </div>
  </div>

</div>

app/views/puppies/new.html.erb
  <div class="hundred-width">
  <div class="row">
    <div class="col-md-6 col-md-push-6 padding hundred-size" style="background-image: linear-gradient(-225deg, rgba(180, 180, 180,0.4) 0%, rgba(120, 120, 120,0.6) 50%), url('<%= asset_path('puppy_new_image.jpg') %>'); background-size: cover;">
      <h1 class="padding1 white-header">Share your puppy today!</h1>
    </div>
    <div class="col-xs-12 col-md-6 col-md-pull-6 padding">
      <%= render "puppies/form", puppy: @puppy%>
    </div>
  </div>
</div>

app/views/puppies/show.html.erb
  <div class="dark-gray">
    <h1><%= @puppy.title %></h1>
  </div>
  <div class="full-width">
    <div class="flex-horizontal">

      <div class="flex-item-left">
        <h2><%= @puppy.name %></h2>
        <p> <%= @puppy.street %>, <%= @puppy.zipcode %>, <%= @puppy.city %>, <%= @puppy.country %></p>
        <ul>
          <li><%= @puppy.description %></li>
        </ul>

        <ul>
          <li><strong>Daily Price:</strong> <%= number_with_precision((@puppy.daily_price.to_f / 100).round(2), precision: 2) %> €</li>
          <li><strong>Birthdate:</strong> <%= @puppy.birthdate.strftime("%d %B %Y") %></li>
          <li><strong>Breed:</strong> <%= @puppy.breed.name %></li>
          <li><strong>Toilet training level:</strong> <%= @puppy.toilet_training_level %></li>
        </ul>
        <br>
        <% if current_user %>
        <% if @puppy.user.id == current_user.id %>
        <%= link_to "Edit", edit_puppy_path, class: "btn btn-danger" %>
        <%= link_to "Delete", puppy_path(@puppy), method: :delete, class: "btn btn-danger" %>
        <% else %>
        <% end %>
        <% end %>

      </div>
      <%= image_tag(@puppy.photo_url, class: "profile-image", alt: "puppy pic") %>
    </div>
  </div>


  <div class="full-width">
    <div class="flex-horizontal">
      <div class="flex-item-left gray-ground">



        <div class="row">
          <% if @puppy.reviews.blank? %>
          <p>There are no reviews for <%= @puppy.name %> yet</p>
          <% else %>

          <% @reviews.each do |review| %>
          <div class="col-xs-12 col-sm-6">
            <div class="review-card">
              <h4><strong>"<%= review.title %>"</strong></h4>
              <p>"<%= review.description.truncate(90) %>"</p>

              <% num = review.rating %>
              <% anum = 5 - review.rating %>
              <% num.times do %>
              <i class="fas fa-star" style="color: #f9d949"></i>
              <% end %>
              <% anum.times do %>
              <i class="far fa-star" style="color: #f9d949"></i>
              <% end %>
            </div>
          </div>
          <% end %>
          <% end %>

        </div>

      </div>


      <div class="flex-item-right gray-ground">
        <% if notice.present? %>
        <p class="notice"> <i class="fas fa-exclamation-triangle"></i><%= notice %></p>
        <% end %>
        <div class="booking-form">
          <h2>Book <%= @puppy.name %> Now</h2>
          <%= render "bookings/form", puppy: @puppy, booking: @booking %>
        </div>


      </div>
    </div>
  </div>